// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDI2_1m-s3NCWokU4OmoR0HtJxTKNzobh8',
    appId: '1:447707051518:web:a832bd86045389dd397caf',
    messagingSenderId: '447707051518',
    projectId: 'account-manager-a986b',
    authDomain: 'account-manager-a986b.firebaseapp.com',
    storageBucket: 'account-manager-a986b.firebasestorage.app',
    measurementId: 'G-DQ3Y0TZK5B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6KpveqaPCJPSVKmP2HThyrLM3szHMSVw',
    appId: '1:447707051518:android:2990e53b624bd02a397caf',
    messagingSenderId: '447707051518',
    projectId: 'account-manager-a986b',
    storageBucket: 'account-manager-a986b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBySILvm6N5Pu4z4Uh3-DyJeJ6C8tHYdKM',
    appId: '1:447707051518:ios:da9caa3e8e373d37397caf',
    messagingSenderId: '447707051518',
    projectId: 'account-manager-a986b',
    storageBucket: 'account-manager-a986b.firebasestorage.app',
    iosBundleId: 'com.example.accountManager',
  );
}
